name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'build'
      - .git

jobs:
  Build_the_markup_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: Checkout guide
        run: |
          mkdir src && cd src
          git clone https://github.com/P0C-demo/income-tax-mtd-end-to-end-service-guide.git
      - name: Install ruby dependencies
        run: |
          cd src/income-tax-mtd-end-to-end-service-guide
          bundle install
      - name: Build static site
        run: |
          cd src/income-tax-mtd-end-to-end-service-guide
          bundle exec middleman build
      - name: Checkout destination
        run: |
          mkdir dest && cd dest
          git clone https://github.com/P0C-demo/P0C-demo.github.io.git
      - name: Check for changes
        id: check_changes
        run: |
          cd src/income-tax-mtd-end-to-end-service-guide/build
          if git diff --exit-code --quiet .; then
            echo "No changes found"  
            echo "changes=false" >> "$GITHUB_ENV"
          else
            echo "changes=true" >> "$GITHUB_ENV"
          fi

      - name: Retrieve markup files
        if: steps.check_changes.changes == 'true'
        run: |
          cp -r src/income-tax-mtd-end-to-end-service-guide/build/* dest/P0C-demo.github.io/   
          cd dest/P0C-demo.github.io
          git config user.name "Github.Action"
          git config user.email "deliverablestangible@gmail.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push https://${{ secrets.PAT }}@github.com/P0C-demo/P0C-demo.github.io.git
